### ISSUE TITLE
http 环境切换 is ok，https find host 后 local and online 环境切换 数据存在缓存

### ISSUE THREAD

**Issue by mj520** [liyangready/multiple-host#13]
http 环境切换 is ok，https find host 后 local and online 环境切换 数据存在缓存、切换数据还是老的环境的数据。求解
怎么 https能否使用透明代理 实现
下载源代码不知道怎么运行，没有说名

**Comment by liyangready** [comment]
https下面 chrome会复用一个 connect，导致更改可能会有缓存问题。

解决方案暂时打开为：chrome://net-internals/#sockets ，选择刷新一下连接 flush-sockets-pool

**Comment by wuwb** [comment]
可以试试用 [mini-proxy](https://github.com/liyangready/mini-proxy) 做代理

**Comment by liyangready** [comment]
找到解决办法了，可以发现host变化时主动断掉socket连接，再次刷新就好了。新版本我做进去。
