### ISSUE TITLE
报错 renderList of underfined

### ISSUE THREAD

**Issue by charisna** [liyangready/multiple-host#3]
日志提示：Cannot read property 'renderList' of undefined

并且代理host界面空白，这个应该如何解决呢？

**Comment by liyangready** [comment]
非常感谢提供反馈，请问您是使用的什么操作系统呢，我这里测试一下~

**Comment by liyangready** [comment]
您能给一个联系方式不，我可能需要排查下问题出在哪里^^

**Comment by charisna** [comment]
用的Win7 X64系统，有一次出现了卡顿（无响应），然后被强制关闭后就出现了描述的情况，我这边把配置文件目录清空了，就好了，不过配置都重新生成了。

**Comment by liyangready** [comment]
哦哦 那应该是在配置文件中写入了非正常格式的配置导致解析失败了 多谢反馈 我之后想想做点容错

在 2016年7月19日 上午9:54，charisna notifications@github.com写道：

**Comment by charisna** [comment]
嗯，多谢。
