### ISSUE TITLE
mac 下 firefox 能启动，但是无法打开Google。同样的方式在chrome上可以打开！

### ISSUE THREAD

**Issue by wcy10586** [liyangready/multiple-host#6]

**Comment by liyangready** [comment]
通过软件启动的chrome可以打开Google？正常都是代理从multiple-host过了，如果是全局的vpn可能可以，否则应该都不能打开Google吧。

不过这个打开的浏览器主要是为了让你测试不同的host的用的，如果需要访问Google，建议使用正常打开的浏览器（即不是通过软件唤起的）

**Comment by wcy10586** [comment]
我正常的打开浏览器，chrome和firefox都打不开google，只有通过软件启动的chrome能打开！
