### ISSUE TITLE
请问可以把postman的请求代理到multiple-host吗？

### ISSUE THREAD

**Issue by yisake** [liyangready/multiple-host#8]
如题

这样postman发出的请求就能使用代理的hosts了。。

**Comment by liyangready** [comment]
可以的，开始使用 - ie及其他 - 打开系统代理，然后再使用 postman 会发现请求是使用了代理host

**Comment by yisake** [comment]
@liyangready 
好的 是这样的 项目怎么学习啊？通过什么编译成exe？主要代码路径是哪个啊？

**Comment by liyangready** [comment]
你看下 node-webkit 通过他编译的，然后主要代码都在 lib 目录下面
